version: '3.9'

services:      
  appgw:
    restart: always    
    build: 
      context: .
      dockerfile: ./BlazorApp1/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5201  # 이 환경변수가 핵심!
    ports:
      - "5201:5201"
    networks:
      - appnetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
networks:
  appnetwork:
    driver: bridge
